### ISSUE TITLE
bug: Cannot communicate with Minikube SSL endpoint

### ISSUE THREAD

**Issue by alanmeadows** [att-comdev/armada#10]
**Is this a bug report or feature request?** (choose one):

**Python Version** (output of `python --version`): 2.7.9

**Development or Deployment Environment?**: MacOS

**Release Tag or Master**: Master

**Expected Behavior**: Armada works per README.md

**What Actually Happened**: Exception when using Minikube

**How to Reproduce the Issue** (as minimally as possible):

Follow README.md.  Several steps such as installing required libraries via brew are missing.  

Finally, when using Minikube, which is not necessarily MacOS specific but typical for these users, the following exception occurs (because of SSL issues with the Minikube API endpoint):

```
$ ~/armada-env/bin/armada -c ~/Workbench/att/armada/examples/armada.yaml
2017-02-27 07:46:40,659 ERROR Certificate did not match expected hostname: 192.168.99.100. Certificate: {'subjectAltName': (('DNS', 'kubernetes.default.svc.cluster.local'), ('DNS', 'kubernetes.default.svc'), ('DNS', 'kubernetes.default'), ('DNS', 'kubernetes'), ('IP Address', '192.168.99.100'), ('IP Address', '10.0.0.1')), 'notBefore': u'Feb 20 13:34:13 2017 GMT', 'serialNumber': u'02', 'notAfter': 'Feb 20 13:34:13 2018 GMT', 'version': 3L, 'subject': ((('commonName', u'minikube'),),), 'issuer': ((('commonName', u'minikubeCA'),),)}
2017-02-27 07:46:40,659 urllib3.connection ERROR    Certificate did not match expected hostname: 192.168.99.100. Certificate: {'subjectAltName': (('DNS', 'kubernetes.default.svc.cluster.local'), ('DNS', 'kubernetes.default.svc'), ('DNS', 'kubernetes.default'), ('DNS', 'kubernetes'), ('IP Address', '192.168.99.100'), ('IP Address', '10.0.0.1')), 'notBefore': u'Feb 20 13:34:13 2017 GMT', 'serialNumber': u'02', 'notAfter': 'Feb 20 13:34:13 2018 GMT', 'version': 3L, 'subject': ((('commonName', u'minikube'),),), 'issuer': ((('commonName', u'minikubeCA'),),)}
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/handlers.py", line 861, in emit
    self.socket.send(msg)
error: [Errno 40] Message too long
Logged from file armada, line 42
2017-02-27 07:46:40,659 armada       ERROR    (0)
Reason: SSLError
hostname '192.168.99.100' doesn't match either of 'kubernetes.default.svc.cluster.local', 'kubernetes.default.svc', 'kubernetes.default', 'kubernetes', '192.168.99.100', '10.0.0.1'
Traceback (most recent call last):
  File "/Users/alan/armada-env/lib/python2.7/site-packages/armada-0.1.0-py2.7.egg/EGG-INFO/scripts/armada", line 39, in <module>
  File "/Users/alan/armada-env/lib/python2.7/site-packages/armada-0.1.0-py2.7.egg/EGG-INFO/scripts/armada", line 29, in run
  File "build/bdist.macosx-10.10-x86_64/egg/armada/armada.py", line 25, in __init__
    self.tiller = Tiller()
  File "build/bdist.macosx-10.10-x86_64/egg/armada/tiller.py", line 23, in __init__
    self.channel = self.get_channel()
  File "build/bdist.macosx-10.10-x86_64/egg/armada/tiller.py", line 43, in get_channel
    tiller_ip = self._get_tiller_ip()
  File "build/bdist.macosx-10.10-x86_64/egg/armada/tiller.py", line 63, in _get_tiller_ip
    pod = self._get_tiller_pod()
  File "build/bdist.macosx-10.10-x86_64/egg/armada/tiller.py", line 52, in _get_tiller_pod
    ret = self.k8s.client.list_pod_for_all_namespaces()
  File "/Users/alan/armada-env/lib/python2.7/site-packages/kubernetes/client/apis/core_v1_api.py", line 13586, in list_pod_for_all_namespaces
    (data) = self.list_pod_for_all_namespaces_with_http_info(**kwargs)
  File "/Users/alan/armada-env/lib/python2.7/site-packages/kubernetes/client/apis/core_v1_api.py", line 13679, in list_pod_for_all_namespaces_with_http_info
    collection_formats=collection_formats)
  File "/Users/alan/armada-env/lib/python2.7/site-packages/kubernetes/client/api_client.py", line 328, in call_api
    _return_http_data_only, collection_formats, _preload_content, _request_timeout)
  File "/Users/alan/armada-env/lib/python2.7/site-packages/kubernetes/client/api_client.py", line 152, in __call_api
    _request_timeout=_request_timeout)
  File "/Users/alan/armada-env/lib/python2.7/site-packages/kubernetes/client/api_client.py", line 351, in request
    headers=headers)
  File "/Users/alan/armada-env/lib/python2.7/site-packages/kubernetes/client/rest.py", line 233, in GET
    query_params=query_params)
  File "/Users/alan/armada-env/lib/python2.7/site-packages/kubernetes/client/rest.py", line 210, in request
    raise ApiException(status=0, reason=msg)
ApiException: (0)
Reason: SSLError
hostname '192.168.99.100' doesn't match either of 'kubernetes.default.svc.cluster.local', 'kubernetes.default.svc', 'kubernetes.default', 'kubernetes', '192.168.99.100', '10.0.0.1'
```

**Any Additional Comments**:

This bug report presumes the following patches are in place allowing Armada to run on MacOS (separate issue):

```
$ git diff
diff --git a/armada/logutil.py b/armada/logutil.py
index abe1422..e9a509e 100644
--- a/armada/logutil.py
+++ b/armada/logutil.py
@@ -11,7 +11,7 @@ LOG_DATE = '%m-%d %H:%M'
 def setup_logging(args):
     level = logging.DEBUG if args.debug else logging.INFO
     logging.basicConfig(level=level, format=LOG_FORMAT, date_fmt=LOG_DATE)
-    handler = SysLogHandler(address='/dev/log')
+    handler = SysLogHandler(address='/var/run/syslog')
     syslog_formatter = logging.Formatter('%(name)s: %(levelname)s %(message)s')
     handler.setFormatter(syslog_formatter)
-    LOG.addHandler(handler)
\ No newline at end of file
+    LOG.addHandler(handler)
diff --git a/requirements.txt b/requirements.txt
index 127ba24..43b6e7f 100644
--- a/requirements.txt
+++ b/requirements.txt
@@ -3,5 +3,5 @@ grpc
 pyyaml
 grpcio
 grpcio-tools
-kubernetes
-pygit2==0.24.0
+kubernetes==1.0.0b1
+pygit2==0.25.0
```

**Comment by gardlt** [comment]
The reason of this issue is that when we do a `python setup.py install` or `pip install` the entry point for the main is set to use `#!/usr/bin/python` which uses an outdated openssl. a hacky fix is to got to the `/usr/local/bin/armada' and point it to the correct python interpreter using and updated openssl.

**Comment by gardlt** [comment]
The fix to this issue is more to do with your environment set up and it will differ from person 2 person. I suggest using our docker solution #20 which is currently WIP.

**Comment by alanmeadows** [comment]
`$ ~/armada-env/bin/armada -c ~/Workbench/att/armada/examples/armada.yaml`

Was using `armada` from a virtualenv, `armada-env` where it was installed with dependencies.  Not sure how the path of `python` either at install time or run time as mentioned above ties into that -- armada and its dependencies were definitely installed to `armada-env`

**Comment by gardlt** [comment]
`python -c "import ssl; print ssl.OPENSSL_VERSION"` run this command in your venv if your ssl is less than 1.0 than that is the issue.
