### ISSUE TITLE
error when deploying some charts, even when formatted correctly

### ISSUE THREAD

**Issue by v1k0d3n** [att-comdev/armada#171]
**Is this a bug report or feature request?** (choose one): Bug

**Python Version** (output of `python --version`): using armada provided container

**Development or Deployment Environment?**: deployment

**Release Tag or Master**: master

**Expected Behavior**: chart would be deployed as expected

**What Actually Happened**:

**How to Reproduce the Issue** (as minimally as possible):

**Any Additional Comments**:
when deploying the a ceph chart from OSH, we're seeing the following error/debug:

```
ubuntu@kubenode01:~/demo$ sudo docker exec armada-newton armada apply /examples/armada-ceph.yaml --debug
2017-10-21 17:45:32.764 264 INFO armada.handlers.armada [-] Performing Pre-Flight Operations
2017-10-21 17:45:32.933 264 ERROR armada [-] Could not find chart group None in armada/Manifest/v1: Exception: Could not find chart group None in armada/Manifest/v1
2017-10-21 17:45:32.933 264 ERROR armada Traceback (most recent call last):
2017-10-21 17:45:32.933 264 ERROR armada   File "/usr/local/lib/python3.5/dist-packages/armada/handlers/manifest.py", line 97, in build_armada_manifest
2017-10-21 17:45:32.933 264 ERROR armada     for iter, group in enumerate(self.manifest.get('data').get(
2017-10-21 17:45:32.933 264 ERROR armada AttributeError: 'NoneType' object has no attribute 'get'
2017-10-21 17:45:32.933 264 ERROR armada
2017-10-21 17:45:32.933 264 ERROR armada During handling of the above exception, another exception occurred:
2017-10-21 17:45:32.933 264 ERROR armada
2017-10-21 17:45:32.933 264 ERROR armada Traceback (most recent call last):
2017-10-21 17:45:32.933 264 ERROR armada   File "/usr/local/lib/python3.5/dist-packages/cliff/app.py", line 400, in run_subcommand
2017-10-21 17:45:32.933 264 ERROR armada     result = cmd.run(parsed_args)
2017-10-21 17:45:32.933 264 ERROR armada   File "/usr/local/lib/python3.5/dist-packages/cliff/command.py", line 97, in run
2017-10-21 17:45:32.933 264 ERROR armada     return self.take_action(parsed_args) or 0
2017-10-21 17:45:32.933 264 ERROR armada   File "/usr/local/lib/python3.5/dist-packages/armada/cli/apply.py", line 63, in take_action
2017-10-21 17:45:32.933 264 ERROR armada     applyCharts(parsed_args)
2017-10-21 17:45:32.933 264 ERROR armada   File "/usr/local/lib/python3.5/dist-packages/armada/cli/apply.py", line 32, in applyCharts
2017-10-21 17:45:32.933 264 ERROR armada     armada.sync()
2017-10-21 17:45:32.933 264 ERROR armada   File "/usr/local/lib/python3.5/dist-packages/armada/handlers/armada.py", line 189, in sync
2017-10-21 17:45:32.933 264 ERROR armada     self.pre_flight_ops()
2017-10-21 17:45:32.933 264 ERROR armada   File "/usr/local/lib/python3.5/dist-packages/armada/handlers/armada.py", line 98, in pre_flight_ops
2017-10-21 17:45:32.933 264 ERROR armada     self.config = self.get_armada_manifest()
2017-10-21 17:45:32.933 264 ERROR armada   File "/usr/local/lib/python3.5/dist-packages/armada/handlers/armada.py", line 77, in get_armada_manifest
2017-10-21 17:45:32.933 264 ERROR armada     return Manifest(self.documents).get_manifest()
2017-10-21 17:45:32.933 264 ERROR armada   File "/usr/local/lib/python3.5/dist-packages/armada/handlers/manifest.py", line 112, in get_manifest
2017-10-21 17:45:32.933 264 ERROR armada     self.build_armada_manifest()
2017-10-21 17:45:32.933 264 ERROR armada   File "/usr/local/lib/python3.5/dist-packages/armada/handlers/manifest.py", line 107, in build_armada_manifest
2017-10-21 17:45:32.933 264 ERROR armada     group, DOCUMENT_MANIFEST))
2017-10-21 17:45:32.933 264 ERROR armada Exception: Could not find chart group None in armada/Manifest/v1
2017-10-21 17:45:32.933 264 ERROR armada
2017-10-21 17:45:32.935 264 CRITICAL armada [-] Unhandled error: Exception: Could not find chart group None in armada/Manifest/v1
2017-10-21 17:45:32.935 264 ERROR armada Traceback (most recent call last):
2017-10-21 17:45:32.935 264 ERROR armada   File "/usr/local/lib/python3.5/dist-packages/armada/handlers/manifest.py", line 97, in build_armada_manifest
2017-10-21 17:45:32.935 264 ERROR armada     for iter, group in enumerate(self.manifest.get('data').get(
2017-10-21 17:45:32.935 264 ERROR armada AttributeError: 'NoneType' object has no attribute 'get'
2017-10-21 17:45:32.935 264 ERROR armada
2017-10-21 17:45:32.935 264 ERROR armada During handling of the above exception, another exception occurred:
2017-10-21 17:45:32.935 264 ERROR armada
2017-10-21 17:45:32.935 264 ERROR armada Traceback (most recent call last):
2017-10-21 17:45:32.935 264 ERROR armada   File "/usr/local/bin/armada", line 10, in <module>
2017-10-21 17:45:32.935 264 ERROR armada     sys.exit(main())
2017-10-21 17:45:32.935 264 ERROR armada   File "/usr/local/lib/python3.5/dist-packages/armada/shell.py", line 50, in main
2017-10-21 17:45:32.935 264 ERROR armada     return ArmadaApp().run(argv)
2017-10-21 17:45:32.935 264 ERROR armada   File "/usr/local/lib/python3.5/dist-packages/cliff/app.py", line 279, in run
2017-10-21 17:45:32.935 264 ERROR armada     result = self.run_subcommand(remainder)
2017-10-21 17:45:32.935 264 ERROR armada   File "/usr/local/lib/python3.5/dist-packages/cliff/app.py", line 400, in run_subcommand
2017-10-21 17:45:32.935 264 ERROR armada     result = cmd.run(parsed_args)
2017-10-21 17:45:32.935 264 ERROR armada   File "/usr/local/lib/python3.5/dist-packages/cliff/command.py", line 97, in run
2017-10-21 17:45:32.935 264 ERROR armada     return self.take_action(parsed_args) or 0
2017-10-21 17:45:32.935 264 ERROR armada   File "/usr/local/lib/python3.5/dist-packages/armada/cli/apply.py", line 63, in take_action
2017-10-21 17:45:32.935 264 ERROR armada     applyCharts(parsed_args)
2017-10-21 17:45:32.935 264 ERROR armada   File "/usr/local/lib/python3.5/dist-packages/armada/cli/apply.py", line 32, in applyCharts
2017-10-21 17:45:32.935 264 ERROR armada     armada.sync()
2017-10-21 17:45:32.935 264 ERROR armada   File "/usr/local/lib/python3.5/dist-packages/armada/handlers/armada.py", line 189, in sync
2017-10-21 17:45:32.935 264 ERROR armada     self.pre_flight_ops()
2017-10-21 17:45:32.935 264 ERROR armada   File "/usr/local/lib/python3.5/dist-packages/armada/handlers/armada.py", line 98, in pre_flight_ops
2017-10-21 17:45:32.935 264 ERROR armada     self.config = self.get_armada_manifest()
2017-10-21 17:45:32.935 264 ERROR armada   File "/usr/local/lib/python3.5/dist-packages/armada/handlers/armada.py", line 77, in get_armada_manifest
2017-10-21 17:45:32.935 264 ERROR armada     return Manifest(self.documents).get_manifest()
2017-10-21 17:45:32.935 264 ERROR armada   File "/usr/local/lib/python3.5/dist-packages/armada/handlers/manifest.py", line 112, in get_manifest
2017-10-21 17:45:32.935 264 ERROR armada     self.build_armada_manifest()
2017-10-21 17:45:32.935 264 ERROR armada   File "/usr/local/lib/python3.5/dist-packages/armada/handlers/manifest.py", line 107, in build_armada_manifest
2017-10-21 17:45:32.935 264 ERROR armada     group, DOCUMENT_MANIFEST))
2017-10-21 17:45:32.935 264 ERROR armada Exception: Could not find chart group None in armada/Manifest/v1
2017-10-21 17:45:32.935 264 ERROR armada
ubuntu@kubenode01:~/demo$
```

**Comment by intlabs** [comment]
This was caused by a lack of the chartgroup in the manifest: https://gist.github.com/v1k0d3n/65b1948a552aeae193602b2851c04259

**Comment by v1k0d3n** [comment]
Yup. Bit of an oversight on my part. Thanks @intlabs
