### ISSUE TITLE
Armada stops with a Tiller Message: b'Upgrade complete'

### ISSUE THREAD

**Issue by jezogwza** [att-comdev/armada#188]
**Is this a bug report or feature request?** (choose one):
BUG REPORT

**Python Version** (output of `python --version`):

**Development or Deployment Environment?**:
Development of Third Party stack using OSH

**Release Tag or Master**:
 quay.io/attcomdev/armada:latest

**Expected Behavior**:
I would expect Armada to skip teh chart,  consider it stable/release/updated and move on to the next.

**What Actually Happened**:
2018-01-05 16:38:58.975 1 CRITICAL armada [-] Unhandled error: armada.exceptions.tiller_exceptions.ReleaseException: Failed to Upgrade release: osh-ceph-config - Tiller Message: b'Upgrade complete'
2018-01-05 16:38:58.975 1 ERROR armada Traceback (most recent call last):
2018-01-05 16:38:58.975 1 ERROR armada   File "/usr/local/lib/python3.5/dist-packages/armada/handlers/tiller.py", line 304, in update_release
2018-01-05 16:38:58.975 1 ERROR armada     metadata=self.metadata)
2018-01-05 16:38:58.975 1 ERROR armada   File "/usr/local/lib/python3.5/dist-packages/grpc/_channel.py", line 492, in __call__
2018-01-05 16:38:58.975 1 ERROR armada     return _end_unary_response_blocking(state, call, False, deadline)
2018-01-05 16:38:58.975 1 ERROR armada   File "/usr/local/lib/python3.5/dist-packages/grpc/_channel.py", line 440, in _end_unary_response_blocking
2018-01-05 16:38:58.975 1 ERROR armada     raise _Rendezvous(state, None, None, deadline)
2018-01-05 16:38:58.975 1 ERROR armada grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.UNKNOWN, parse error in "ceph/charts/helm-toolkit/utils/_to_kv_list.tpl": template: ceph/charts/helm-toolkit/utils/_to_kv_list.tpl:1: function "regexMatch" not defined)>
2018-01-05 16:38:58.975 1 ERROR armada 
2018-01-05 16:38:58.975 1 ERROR armada During handling of the above exception, another exception occurred:
2018-01-05 16:38:58.975 1 ERROR armada 
2018-01-05 16:38:58.975 1 ERROR armada Traceback (most recent call last):
2018-01-05 16:38:58.975 1 ERROR armada   File "/usr/local/bin/armada", line 10, in <module>
2018-01-05 16:38:58.975 1 ERROR armada     sys.exit(main())
2018-01-05 16:38:58.975 1 ERROR armada   File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 722, in __call__
2018-01-05 16:38:58.975 1 ERROR armada     return self.main(*args, **kwargs)
2018-01-05 16:38:58.975 1 ERROR armada   File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 697, in main
2018-01-05 16:38:58.975 1 ERROR armada     rv = self.invoke(ctx)
2018-01-05 16:38:58.975 1 ERROR armada   File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 1066, in invoke
2018-01-05 16:38:58.975 1 ERROR armada     return _process_result(sub_ctx.command.invoke(sub_ctx))
2018-01-05 16:38:58.975 1 ERROR armada   File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 895, in invoke
2018-01-05 16:38:58.975 1 ERROR armada     return ctx.invoke(self.callback, **ctx.params)
2018-01-05 16:38:58.975 1 ERROR armada   File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 535, in invoke
2018-01-05 16:38:58.975 1 ERROR armada     return callback(*args, **kwargs)
2018-01-05 16:38:58.975 1 ERROR armada   File "/usr/local/lib/python3.5/dist-packages/click/decorators.py", line 17, in new_func
2018-01-05 16:38:58.975 1 ERROR armada     return f(get_current_context(), *args, **kwargs)
2018-01-05 16:38:58.975 1 ERROR armada   File "/usr/local/lib/python3.5/dist-packages/armada/cli/apply.py", line 120, in apply_create
2018-01-05 16:38:58.975 1 ERROR armada     wait).invoke()
2018-01-05 16:38:58.975 1 ERROR armada   File "/usr/local/lib/python3.5/dist-packages/armada/cli/apply.py", line 186, in invoke
2018-01-05 16:38:58.975 1 ERROR armada     resp = armada.sync()
2018-01-05 16:38:58.975 1 ERROR armada   File "/usr/local/lib/python3.5/dist-packages/armada/handlers/armada.py", line 303, in sync
2018-01-05 16:38:58.975 1 ERROR armada     timeout=chart_timeout)
2018-01-05 16:38:58.975 1 ERROR armada   File "/usr/local/lib/python3.5/dist-packages/armada/handlers/tiller.py", line 307, in update_release
2018-01-05 16:38:58.975 1 ERROR armada     raise ex.ReleaseException(release, status, 'Upgrade')
2018-01-05 16:38:58.975 1 ERROR armada armada.exceptions.tiller_exceptions.ReleaseException: Failed to Upgrade release: osh-ceph-config - Tiller Message: b'Upgrade complete'
2018-01-05 16:38:58.975 1 ERROR armada 
**How to Reproduce the Issue** (as minimally as possible):
Not sure. I deployed OSH, had some issues. Cleaned some things, and was trying to re apply the manifest to finish the deployment.

**Any Additional Comments**:

**Comment by MarshM** [comment]
Spoke with @jezogwza offline, closing this as it hasn't been experienced in a while.
