### ISSUE TITLE
how to deploy openstack with armada which is deployed using promenade?

### ISSUE THREAD

**Issue by pratapaprasanna** [att-comdev/armada#203]
**Is this a bug report or feature request?** (choose one): help wanted

**Python Version** (output of `python --version`): 2.7.12

**Development or Deployment Environment?**: Ubuntu 16.04

**Release Tag or Master**:

**Expected Behavior**:

**What Actually Happened**:  Installed Promenade and when i try 
`armada --token $TOKEN apply ./armada_part_2_latest.yaml `
armada_part_2_latest_contains contents of 
[armada_osh](https://github.com/openstack/openstack-helm/blob/766ada1091bced5654887f73cf1817228bf6555b/tools/deployment/armada/multinode/armada-osh.yaml)

**How to Reproduce the Issue** (as minimally as possible):
```
$ armada --token $TOKEN apply ./armada_part_2_latest.yaml 
+ CMD=armada
+ ARMADA_API_PORT=8000
+ ARMADA_API_TIMEOUT=3600
+ ARMADA_API_WORKERS=4
+ ARMADA_API_THREADS=1
+ '[' --token = server ']'
+ exec armada --token gAAAAABa4W5KyFpT2shq4k2qsNFgY-52eXRTt6HQPO1uDJbbK5fRCzFNTVvjDuwDjt6_w8yHcwgoYWCR7b_KyRTUoSJU0VhUdk6ayXmDhBFJTzs8KiPIzoBaoLCMgXoROmcS236iBwfDNuVn6rilIEmvd25V6iE5847SF6L3dDmWefvzFdZnDCc apply ./armada_part_2_latest.yaml
2018-04-26 06:19:24.898 1 ERROR armada.cli [-] Caught unexpected exception: FileNotFoundError: [Errno 2] No such file or directory: './armada_part_2_latest.yaml'
2018-04-26 06:19:24.898 1 ERROR armada.cli Traceback (most recent call last):
2018-04-26 06:19:24.898 1 ERROR armada.cli   File "/usr/local/lib/python3.5/site-packages/armada/cli/__init__.py", line 40, in safe_invoke
2018-04-26 06:19:24.898 1 ERROR armada.cli     self.invoke()
2018-04-26 06:19:24.898 1 ERROR armada.cli   File "/usr/local/lib/python3.5/site-packages/armada/cli/apply.py", line 192, in invoke
2018-04-26 06:19:24.898 1 ERROR armada.cli     doc_data = ReferenceResolver.resolve_reference(self.locations)
2018-04-26 06:19:24.898 1 ERROR armada.cli   File "/usr/local/lib/python3.5/site-packages/armada/handlers/document.py", line 65, in resolve_reference
2018-04-26 06:19:24.898 1 ERROR armada.cli     data.append(handler.__get__(None, cls)(design_uri))
2018-04-26 06:19:24.898 1 ERROR armada.cli   File "/usr/local/lib/python3.5/site-packages/armada/handlers/document.py", line 108, in resolve_reference_file
2018-04-26 06:19:24.898 1 ERROR armada.cli     with open(design_uri.path, 'rb') as f:
2018-04-26 06:19:24.898 1 ERROR armada.cli FileNotFoundError: [Errno 2] No such file or directory: './armada_part_2_latest.yaml'
2018-04-26 06:19:24.898 1 ERROR armada.cli 



```
**Any Additional Comments**:
Any help would be of so much help....!!!!! Stuck here for a couple of days 

Thanks in advance.
Goutham

**Comment by MarshM** [comment]
I suspect this is due to Armada not finding the file you're passing into the container.

You may want to look at Armada's `docker run` command (probably at `/usr/local/bin/armada`, but you can make sure with `which armada`) and add a new volume mount if necessary from your local working to a path inside the container.  Then you should specify the container path when you run it again.

Please let me know if this helps.

**Comment by pratapaprasanna** [comment]
Sure will update as soon as i try :+1:

**Comment by pratapaprasanna** [comment]
`sudo docker run -t --rm --net=host -e http_proxy= -e https_proxy= -e OS_AUTH_URL=http://keystone.ucp.svc.cluster.local:80/v3 -e OS_USERNAME=shipyard -e OS_USER_DOMAIN_NAME=default -e OS_PASSWORD=password18 -e OS_PROJECT_DOMAIN_NAME=default -e OS_PROJECT_NAME=service -v /root/deploy/site:/home/shipyard/host quay.io/attcomdev/shipyard:latest create configdocs design --filename=/home/shipyard/host/deployment_files.yaml`


This is something which i have noticed in airship in a bottle script so after the installation of UCP components we have to start with the help of this... We can refer to airship in a bottle [](https://github.com/openstack/airship-in-a-bottle) to verify and try.
