### ISSUE TITLE
Tiller Pod Missing causes Unhandled Exception

### ISSUE THREAD

**Issue by alanmeadows** [att-comdev/armada#72]
Using the armada:latest container, if tiller is not running at all, the following exception results:

```
root@csolabAIC-80:~/demo# ./armada_push.sh base.yaml --debug
2017-06-17 15:59:05.372 1 ERROR armada [-] 'NoneType' object has no attribute 'status': AttributeError: 'NoneType' object has no attribute 'status'
2017-06-17 15:59:05.372 1 ERROR armada Traceback (most recent call last):
2017-06-17 15:59:05.372 1 ERROR armada   File "/usr/local/lib/python2.7/dist-packages/cliff/app.py", line 400, in run_subcommand
2017-06-17 15:59:05.372 1 ERROR armada     result = cmd.run(parsed_args)
2017-06-17 15:59:05.372 1 ERROR armada   File "/usr/local/lib/python2.7/dist-packages/cliff/command.py", line 97, in run
2017-06-17 15:59:05.372 1 ERROR armada     return self.take_action(parsed_args) or 0
2017-06-17 15:59:05.372 1 ERROR armada   File "/root/armada/armada/cli/apply.py", line 53, in take_action
2017-06-17 15:59:05.372 1 ERROR armada     applyCharts(parsed_args)
2017-06-17 15:59:05.372 1 ERROR armada   File "/root/armada/armada/cli/apply.py", line 30, in applyCharts
2017-06-17 15:59:05.372 1 ERROR armada     args.dry_run)
2017-06-17 15:59:05.372 1 ERROR armada   File "/root/armada/armada/handlers/armada.py", line 60, in __init__
2017-06-17 15:59:05.372 1 ERROR armada     self.tiller = Tiller()
2017-06-17 15:59:05.372 1 ERROR armada   File "/root/armada/armada/handlers/tiller.py", line 51, in __init__
2017-06-17 15:59:05.372 1 ERROR armada     self.channel = self.get_channel()
2017-06-17 15:59:05.372 1 ERROR armada   File "/root/armada/armada/handlers/tiller.py", line 69, in get_channel
2017-06-17 15:59:05.372 1 ERROR armada     tiller_ip = self._get_tiller_ip()
2017-06-17 15:59:05.372 1 ERROR armada   File "/root/armada/armada/handlers/tiller.py", line 88, in _get_tiller_ip
2017-06-17 15:59:05.372 1 ERROR armada     return pod.status.pod_ip
2017-06-17 15:59:05.372 1 ERROR armada AttributeError: 'NoneType' object has no attribute 'status'
2017-06-17 15:59:05.372 1 ERROR armada
2017-06-17 15:59:05.375 1 CRITICAL armada [-] Unhandled error: AttributeError: 'NoneType' object has no attribute 'status'
2017-06-17 15:59:05.375 1 ERROR armada Traceback (most recent call last):
2017-06-17 15:59:05.375 1 ERROR armada   File "/usr/local/bin/armada", line 10, in <module>
2017-06-17 15:59:05.375 1 ERROR armada     sys.exit(main())
2017-06-17 15:59:05.375 1 ERROR armada   File "/root/armada/armada/shell.py", line 43, in main
2017-06-17 15:59:05.375 1 ERROR armada     return ArmadaApp().run(argv)
2017-06-17 15:59:05.375 1 ERROR armada   File "/usr/local/lib/python2.7/dist-packages/cliff/app.py", line 279, in run
2017-06-17 15:59:05.375 1 ERROR armada     result = self.run_subcommand(remainder)
2017-06-17 15:59:05.375 1 ERROR armada   File "/usr/local/lib/python2.7/dist-packages/cliff/app.py", line 400, in run_subcommand
2017-06-17 15:59:05.375 1 ERROR armada     result = cmd.run(parsed_args)
2017-06-17 15:59:05.375 1 ERROR armada   File "/usr/local/lib/python2.7/dist-packages/cliff/command.py", line 97, in run
2017-06-17 15:59:05.375 1 ERROR armada     return self.take_action(parsed_args) or 0
2017-06-17 15:59:05.375 1 ERROR armada   File "/root/armada/armada/cli/apply.py", line 53, in take_action
2017-06-17 15:59:05.375 1 ERROR armada     applyCharts(parsed_args)
2017-06-17 15:59:05.375 1 ERROR armada   File "/root/armada/armada/cli/apply.py", line 30, in applyCharts
2017-06-17 15:59:05.375 1 ERROR armada     args.dry_run)
2017-06-17 15:59:05.375 1 ERROR armada   File "/root/armada/armada/handlers/armada.py", line 60, in __init__
2017-06-17 15:59:05.375 1 ERROR armada     self.tiller = Tiller()
2017-06-17 15:59:05.375 1 ERROR armada   File "/root/armada/armada/handlers/tiller.py", line 51, in __init__
2017-06-17 15:59:05.375 1 ERROR armada     self.channel = self.get_channel()
2017-06-17 15:59:05.375 1 ERROR armada   File "/root/armada/armada/handlers/tiller.py", line 69, in get_channel
2017-06-17 15:59:05.375 1 ERROR armada     tiller_ip = self._get_tiller_ip()
2017-06-17 15:59:05.375 1 ERROR armada   File "/root/armada/armada/handlers/tiller.py", line 88, in _get_tiller_ip
2017-06-17 15:59:05.375 1 ERROR armada     return pod.status.pod_ip
2017-06-17 15:59:05.375 1 ERROR armada AttributeError: 'NoneType' object has no attribute 'status'
2017-06-17 15:59:05.375 1 ERROR armada
```

**Comment by gardlt** [comment]
can you please state scenario or how to reproduce? I have not been able to reproduce.

**Comment by gardlt** [comment]
[ ] move pre-flight check higher in sync
